{{ config(alias=fec_table_alias('oppexp')) }}

-- Operating expenditures. Numeric/date cleanup happens here so downstream
-- models can query typed DuckDB columns instead of raw text fields.
select
    CMTE_ID,
    AMNDT_IND,
    try_cast(nullif(trim(RPT_YR), '') as smallint) as RPT_YR,
    RPT_TP,
    IMAGE_NUM,
    LINE_NUM,
    FORM_TP_CD,
    SCHED_TP_CD,
    NAME,
    CITY,
    STATE,
    ZIP_CODE,
    cast(try_strptime(nullif(trim(TRANSACTION_DT), ''), '%m%d%Y') as date) as TRANSACTION_DT,
    try_cast(nullif(trim(TRANSACTION_AMT), '') as decimal(14,2)) as TRANSACTION_AMT,
    TRANSACTION_PGI,
    PURPOSE,
    CATEGORY,
    CATEGORY_DESC,
    MEMO_CD,
    MEMO_TEXT,
    ENTITY_TP,
    try_cast(nullif(trim(SUB_ID), '') as bigint) as SUB_ID,
    try_cast(nullif(trim(FILE_NUM), '') as bigint) as FILE_NUM,
    TRAN_ID,
    BACK_REF_TRAN_ID
from read_csv(
    '{{ fec_source_path("oppexp", "oppexp.txt") }}',
    delim='|',
    header=false,
    all_varchar=true,
    null_padding=true,
    ignore_errors=true,
    sample_size=-1,
    columns={
        'CMTE_ID':'VARCHAR',
        'AMNDT_IND':'VARCHAR',
        'RPT_YR':'VARCHAR',
        'RPT_TP':'VARCHAR',
        'IMAGE_NUM':'VARCHAR',
        'LINE_NUM':'VARCHAR',
        'FORM_TP_CD':'VARCHAR',
        'SCHED_TP_CD':'VARCHAR',
        'NAME':'VARCHAR',
        'CITY':'VARCHAR',
        'STATE':'VARCHAR',
        'ZIP_CODE':'VARCHAR',
        'TRANSACTION_DT':'VARCHAR',
        'TRANSACTION_AMT':'VARCHAR',
        'TRANSACTION_PGI':'VARCHAR',
        'PURPOSE':'VARCHAR',
        'CATEGORY':'VARCHAR',
        'CATEGORY_DESC':'VARCHAR',
        'MEMO_CD':'VARCHAR',
        'MEMO_TEXT':'VARCHAR',
        'ENTITY_TP':'VARCHAR',
        'SUB_ID':'VARCHAR',
        'FILE_NUM':'VARCHAR',
        'TRAN_ID':'VARCHAR',
        'BACK_REF_TRAN_ID':'VARCHAR'
    }
)
