{{ config(alias=fec_table_alias('weball')) }}

-- Candidate summary totals. The FEC field name GEN_ELECTION_PRECENT is kept
-- as-is to match the source layout and the existing PowerShell loader.
select
    CAND_ID,
    CAND_NAME,
    CAND_ICI,
    PTY_CD,
    CAND_PTY_AFFILIATION,
    try_cast(nullif(trim(TTL_RECEIPTS), '') as decimal(14,2)) as TTL_RECEIPTS,
    try_cast(nullif(trim(TRANS_FROM_AUTH), '') as decimal(14,2)) as TRANS_FROM_AUTH,
    try_cast(nullif(trim(TTL_DISB), '') as decimal(14,2)) as TTL_DISB,
    try_cast(nullif(trim(TRANS_TO_AUTH), '') as decimal(14,2)) as TRANS_TO_AUTH,
    try_cast(nullif(trim(COH_BOP), '') as decimal(14,2)) as COH_BOP,
    try_cast(nullif(trim(COH_COP), '') as decimal(14,2)) as COH_COP,
    try_cast(nullif(trim(CAND_CONTRIB), '') as decimal(14,2)) as CAND_CONTRIB,
    try_cast(nullif(trim(CAND_LOANS), '') as decimal(14,2)) as CAND_LOANS,
    try_cast(nullif(trim(OTHER_LOANS), '') as decimal(14,2)) as OTHER_LOANS,
    try_cast(nullif(trim(CAND_LOAN_REPAY), '') as decimal(14,2)) as CAND_LOAN_REPAY,
    try_cast(nullif(trim(OTHER_LOAN_REPAY), '') as decimal(14,2)) as OTHER_LOAN_REPAY,
    try_cast(nullif(trim(DEBTS_OWED_BY), '') as decimal(14,2)) as DEBTS_OWED_BY,
    try_cast(nullif(trim(TTL_INDIV_CONTRIB), '') as decimal(14,2)) as TTL_INDIV_CONTRIB,
    CAND_OFFICE_ST,
    CAND_OFFICE_DISTRICT,
    SPEC_ELECTION,
    PRIM_ELECTION,
    RUN_ELECTION,
    GEN_ELECTION,
    try_cast(nullif(trim(GEN_ELECTION_PRECENT), '') as decimal(7,4)) as GEN_ELECTION_PRECENT,
    try_cast(nullif(trim(OTHER_POL_CMTE_CONTRIB), '') as decimal(14,2)) as OTHER_POL_CMTE_CONTRIB,
    try_cast(nullif(trim(POL_PTY_CONTRIB), '') as decimal(14,2)) as POL_PTY_CONTRIB,
    coalesce(
        cast(try_strptime(nullif(trim(CVG_END_DT), ''), '%m/%d/%Y') as date),
        cast(try_strptime(nullif(trim(CVG_END_DT), ''), '%m%d%Y') as date)
    ) as CVG_END_DT,
    try_cast(nullif(trim(INDIV_REFUNDS), '') as decimal(14,2)) as INDIV_REFUNDS,
    try_cast(nullif(trim(CMTE_REFUNDS), '') as decimal(14,2)) as CMTE_REFUNDS
from read_csv(
    '{{ fec_source_path("weball", "weball" ~ fec_cycle_suffix() ~ ".txt") }}',
    delim='|',
    header=false,
    all_varchar=true,
    null_padding=true,
    ignore_errors=true,
    sample_size=-1,
    columns={
        'CAND_ID':'VARCHAR',
        'CAND_NAME':'VARCHAR',
        'CAND_ICI':'VARCHAR',
        'PTY_CD':'VARCHAR',
        'CAND_PTY_AFFILIATION':'VARCHAR',
        'TTL_RECEIPTS':'VARCHAR',
        'TRANS_FROM_AUTH':'VARCHAR',
        'TTL_DISB':'VARCHAR',
        'TRANS_TO_AUTH':'VARCHAR',
        'COH_BOP':'VARCHAR',
        'COH_COP':'VARCHAR',
        'CAND_CONTRIB':'VARCHAR',
        'CAND_LOANS':'VARCHAR',
        'OTHER_LOANS':'VARCHAR',
        'CAND_LOAN_REPAY':'VARCHAR',
        'OTHER_LOAN_REPAY':'VARCHAR',
        'DEBTS_OWED_BY':'VARCHAR',
        'TTL_INDIV_CONTRIB':'VARCHAR',
        'CAND_OFFICE_ST':'VARCHAR',
        'CAND_OFFICE_DISTRICT':'VARCHAR',
        'SPEC_ELECTION':'VARCHAR',
        'PRIM_ELECTION':'VARCHAR',
        'RUN_ELECTION':'VARCHAR',
        'GEN_ELECTION':'VARCHAR',
        'GEN_ELECTION_PRECENT':'VARCHAR',
        'OTHER_POL_CMTE_CONTRIB':'VARCHAR',
        'POL_PTY_CONTRIB':'VARCHAR',
        'CVG_END_DT':'VARCHAR',
        'INDIV_REFUNDS':'VARCHAR',
        'CMTE_REFUNDS':'VARCHAR'
    }
)
