DROP TABLE IF EXISTS {TARGET_TABLE};
CREATE TABLE {TARGET_TABLE} AS
SELECT
    CMTE_ID,
    AMNDT_IND,
    TRY_CAST(NULLIF(TRIM(RPT_YR), '') AS SMALLINT) AS RPT_YR,
    RPT_TP,
    IMAGE_NUM,
    LINE_NUM,
    FORM_TP_CD,
    SCHED_TP_CD,
    NAME,
    CITY,
    STATE,
    NULLIF(SUBSTR(TRIM(ZIP_CODE), 1, 5), '') AS ZIP_CODE,
    CAST(TRY_STRPTIME(NULLIF(TRIM(TRANSACTION_DT), ''), '%m%d%Y') AS DATE) AS TRANSACTION_DT,
    TRY_CAST(NULLIF(TRIM(TRANSACTION_AMT), '') AS DECIMAL(14,2)) AS TRANSACTION_AMT,
    TRANSACTION_PGI,
    PURPOSE,
    CATEGORY,
    CATEGORY_DESC,
    MEMO_CD,
    MEMO_TEXT,
    ENTITY_TP,
    TRY_CAST(NULLIF(TRIM(SUB_ID), '') AS BIGINT) AS SUB_ID,
    TRY_CAST(NULLIF(TRIM(FILE_NUM), '') AS BIGINT) AS FILE_NUM,
    TRAN_ID,
    BACK_REF_TRAN_ID
FROM read_csv(
    '{SOURCE_PATH}',
    delim='|',
    header=false,
    all_varchar=true,
    null_padding=true,
    ignore_errors=true,
    sample_size=-1,
    columns={
        'CMTE_ID':'VARCHAR',
        'AMNDT_IND':'VARCHAR',
        'RPT_YR':'VARCHAR',
        'RPT_TP':'VARCHAR',
        'IMAGE_NUM':'VARCHAR',
        'LINE_NUM':'VARCHAR',
        'FORM_TP_CD':'VARCHAR',
        'SCHED_TP_CD':'VARCHAR',
        'NAME':'VARCHAR',
        'CITY':'VARCHAR',
        'STATE':'VARCHAR',
        'ZIP_CODE':'VARCHAR',
        'TRANSACTION_DT':'VARCHAR',
        'TRANSACTION_AMT':'VARCHAR',
        'TRANSACTION_PGI':'VARCHAR',
        'PURPOSE':'VARCHAR',
        'CATEGORY':'VARCHAR',
        'CATEGORY_DESC':'VARCHAR',
        'MEMO_CD':'VARCHAR',
        'MEMO_TEXT':'VARCHAR',
        'ENTITY_TP':'VARCHAR',
        'SUB_ID':'VARCHAR',
        'FILE_NUM':'VARCHAR',
        'TRAN_ID':'VARCHAR',
        'BACK_REF_TRAN_ID':'VARCHAR'
    }
);
